### ISSUE TITLE
parseCsv: Empty, last column not detected

### ISSUE THREAD

**Issue by valentinilk** [sergejsha/csv#1]
Thanks for the library! Added it to one of my projects yesterday.

Just noticed a small bug where `parseCsv` will not detect the last column, if it is empty.

```
year,make,model,price
1997,Ford,E350,3000.00
1999,Chevy,Venture,
```

In this sample the library will only detect 3 columns in the last row. The trailing comma seems to be ignored.

**Comment by sergejsha** [comment]
Thanks for reporting! The fix is out in release 0.7.
